Type: AWS::ECS::Service
Properties:
  CapacityProviderStrategy:
    - CapacityProviderStrategyItem
  Cluster: String
  DeploymentConfiguration: DeploymentConfiguration
  DeploymentController: DeploymentController
  DesiredCount: Integer
  EnableECSManagedTags: Boolean
  EnableExecuteCommand: Boolean
  HealthCheckGracePeriodSeconds: Integer
  LaunchType: String
  LoadBalancers:
    - LoadBalancer
  NetworkConfiguration: NetworkConfiguration
  PlacementConstraints:
    - PlacementConstraint
  PlacementStrategies:
    - PlacementStrategy
  PlatformVersion: String
  PropagateTags: String
  Role: String
  SchedulingStrategy: String
  ServiceConnectConfiguration: ServiceConnectConfiguration
  ServiceName: String
  ServiceRegistries:
    - ServiceRegistry
  Tags:
    - Tag
  TaskDefinition: String
