name: '[build] trigger docker image build'
on: [push]

jobs:
  check-variable:
    runs-on: ubuntu-latest
    env:
      CUR_GITHUB_REF: ${{github.ref_name}}
    steps:
      - name: show-variable
        run: |
          echo $CUR_GITHUB_REF

  check-target-branch-develop:
    if: github.ref_name == vars.TARGET_BRANCH
    environment: develop
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ vars.TARGET_BRANCH }}
    steps:
      - name: TEST
        run: |
          echo "dev"
          echo $TARGET_BRANCH

  check-target-branch-prod:
    if: github.ref_name == vars.TARGET_BRANCH
    environment: production
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ vars.TARGET_BRANCH }}
    steps:
      - name: TEST
        run: |
          echo "prod"
          echo $TARGET_BRANCH
