name: '[BUILD] trigger docker image build'
on: [push]

jobs:
  check-variable:
    runs-on: ubuntu-latest
    env:
      CUR_GITHUB_REF: ${{github.ref_name}}
    steps:
      - name: show-variable
        run: |
          echo $CUR_GITHUB_REF

  check-target-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production, develop]
    env:
      CURRENT_BRANCH: ${{ github.ref_name }}
    steps:
      - name: set TARGET_BRANCH based on ${{ matrix.environment }}
        run: |
          if [ "${{ matrix.environment }}" == "production" ]; then
            echo "TARGET_BRANCH=main" >> $GITHUB_ENV
          elif [ "${{ matrix.environment }}" == "develop" ]; then
            echo "TARGET_BRANCH=develop" >> $GITHUB_ENV
          fi
      - name: check ${{ matrix.environment }}
        run: |
          if [ "$CURRENT_BRANCH" == "$TARGET_BRANCH" ]; then
            echo "$CURRENT_BRANCH $TARGET_BRANCH trigger build"
          fi
