name: '[BUILD] trigger docker image build'
on: [push]

jobs:
  check-variable:
    runs-on: ubuntu-latest
    env:
      CUR_GITHUB_REF: ${{github.ref_name}}
    steps:
      - name: show-variable
        run: |
          echo $CUR_GITHUB_REF

  check-target-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production, develop]
    env:
      CURRENT_BRANCH: ${{ github.ref_name }}
      TARGET_BRANCH: ${{ vars.TARGET_BRANCH }}
    steps:
      - name: check ${{ matrix.environment }}
        run: |
          if [ "$CURRENT_BRANCH" == "$TARGET_BRANCH" ]; then
            echo "$CURRENT_BRANCH $TARGET_BRANCH trigger build"
          fi
