name: 'Trigger docker image build'
on: [push]

env:
  REPO: ${{ github.repository }}
  TARGET_WORK_FLOW_FILE: docker-image-ci.yml
  GITHUB_SECRET: ${{ secrets.WORKFLOW_PAT }}

jobs:
  check-variable:
    runs-on: ubuntu-latest
    env:
      CUR_GITHUB_REF: ${{github.ref_name}}
    steps:
      - name: show-variable
        run: |
          echo $CUR_GITHUB_REF

  check-target-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod, dev]
    environment: ${{ matrix.environment }}
    steps:
      - name: trigger docker build ${{ matrix.environment }}
        run: |
          if [ "${{ github.ref_name }}" == "${{ vars.TARGET_BRANCH }}" ]; then
          echo "https://api.github.com/repos/$REPO/actions/workflows/$TARGET_WORK_FLOW_FILE/dispatches"
          echo "{"ref":"${{ vars.TARGET_BRANCH }}","inputs":{"phase":"${{ matrix.environment }}"}}"
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_SECRET" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO/actions/workflows/$TARGET_WORK_FLOW_FILE/dispatches \
            -d "{\"ref\":\"${{ vars.TARGET_BRANCH }}\",\"inputs\":{\"phase\":\"${{ matrix.environment }}\"}}"
          fi
